name: Build xxhash Android wheel for Chaquopy

on:
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Python version'
        required: false
        default: '3.13'
      ndk_version:
        description: 'Android NDK version'
        required: false
        default: 'r26d'
      android_api:
        description: 'Android API level'
        required: false
        default: '24'
      xxhash_version:
        description: 'xxhash version tag (optional, uses latest if not specified)'
        required: false
  push:
    paths:
      - '.github/workflows/build-xxhash-android.yml'
      - '.github/workflows/build-android-wheel.yml'

jobs:
  build-xxhash:
    uses: ./.github/workflows/build-android-wheel.yml
    permissions:
      contents: write
      actions: write
    with:
      library-name: 'xxhash'
      git-repository: 'ifduyue/python-xxhash'
      library-version: ${{ github.event.inputs.xxhash_version }}
      python-version: ${{ github.event.inputs.python_version || '3.13' }}
      android-api: ${{ github.event.inputs.android_api || '24' }}
