name: Reusable - Build Android Wheel with cibuildwheel

on:
  workflow_call:
    inputs:
      library-name:
        description: 'Name of the library (e.g., zstandard)'
        required: true
        type: string
      git-repository:
        description: 'Git repository of the library source (e.g., indygreg/python-zstandard)'
        required: true
        type: string
      library-version:
        description: 'Git ref (tag/branch) of the library version. Uses default branch if empty.'
        required: false
        type: string
      source-dir:
        description: 'Subdirectory containing pyproject.toml or setup.py'
        required: false
        type: string
        default: '.'
      python-version:
        description: 'Python version (e.g., 3.13)'
        required: false
        type: string
        default: '3.13'
      android-api:
        description: 'Android API level'
        required: false
        type: string
        default: '24'

jobs:
  build_android_wheels:
    name: Build wheel for ${{ matrix.abi }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        abi: [arm64_v8a, x86_64]

    steps:
      - name: Clone library source
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.git-repository }}
          ref: ${{ inputs.library-version }}
          path: library-source
          submodules: recursive

      - name: Prepare cibuildwheel environment
        run: |
          PYTHON_VERSION_NODOT=$(echo "${{ inputs.python-version }}" | tr -d '.')
          echo "CIBW_BUILD=cp${PYTHON_VERSION_NODOT}-*" >> $GITHUB_ENV

      - name: Build wheels with cibuildwheel
        uses: pypa/cibuildwheel@v3.2.1
        with:
          package-dir: library-source/${{ inputs.source-dir }}
        env:
          # Tell cibuildwheel to build for Android
          CIBW_PLATFORM: android

          # Set the architectures to build for
          CIBW_ARCHS: ${{ matrix.abi }}

          # CIBW_BUILD is set in the previous step

          # Set the Android API level
          CIBW_ENVIRONMENT: 'ANDROID_API_LEVEL=${{ inputs.android-api }}'
          
          # Add verbosity for better debugging
          CIBW_BUILD_VERBOSITY: 1

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.library-name }}-android-wheel-${{ matrix.abi }}
          path: ./wheelhouse/*.whl
