name: Reusable - Build Android Wheel (Python Script)

on:
  workflow_call:
    inputs:
      library-name:
        description: 'Name of the library'
        required: true
        type: string
      git-repository:
        description: 'Git repository of the library source'
        required: true
        type: string
      library-version:
        description: 'Git ref (tag/branch) of the library version'
        required: false
        type: string
      source-dir:
        description: 'Subdirectory containing pyproject.toml or setup.py'
        required: false
        type: string
        default: '.'
      python-version:
        description: 'Python version (e.g., 3.13)'
        required: false
        type: string
        default: '3.13'
      android-api:
        description: 'Android API level'
        required: false
        type: string
        default: '24'

jobs:
  build:
    name: Build for ${{ matrix.abi }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - abi: "arm64-v8a"
            target: "aarch64-linux-android"
          - abi: "x86_64"
            target: "x86_64-linux-android"

    steps:
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Checkout self
        uses: actions/checkout@v4

      - name: Run build script
        env:
          CIBW_LIBRARY_NAME: ${{ inputs.library-name }}
          CIBW_GIT_REPOSITORY: ${{ inputs.git-repository }}
          CIBW_LIBRARY_VERSION: ${{ inputs.library-version }}
          CIBW_SOURCE_DIR: ${{ inputs.source-dir }}
          CIBW_PYTHON_VERSION: ${{ inputs.python-version }}
          CIBW_ANDROID_API: ${{ inputs.android-api }}
          CIBW_TARGET_ABI: ${{ matrix.abi }}
          CIBW_TARGET_TRIPLET: ${{ matrix.target }}
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          chmod +x .github/scripts/build/build_android_wheel.py
          uv run --python 3.11 --with build .github/scripts/build/build_android_wheel.py

  upload-wheels:
    name: Upload Wheels
    needs: build
    runs-on: ubuntu-latest
    concurrency:
      group: wheels-branch-update
      cancel-in-progress: false
    permissions:
      contents: write
      actions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download all wheel artifacts
        uses: actions/download-artifact@v4
        with:
          path: wheels
          pattern: ${{ env.LIBRARY_NAME }}-android-wheel-*
          merge-multiple: true
      - name: Commit wheels to 'wheels' branch
        run: |
          set -ex
          if [ ! -d "wheels" ] || [ -z "$(ls -A wheels)" ]; then
            echo "No wheels to commit"
            exit 0
          fi

          mkdir wheels_repo
          cd wheels_repo

          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"

          if git fetch --depth=1 origin wheels && git checkout wheels; then
            echo "Checked out existing 'wheels' branch."
          else
            echo "Creating new 'wheels' branch."
            git checkout -b wheels
          fi

          cp ../wheels/* .

          git add .
          if git diff --staged --quiet; then
            echo "No new or updated wheels to commit."
            exit 0
          fi
          git commit -m "Build: Add/Update ${{ env.LIBRARY_NAME }} wheels for version ${{ env.LIBRARY_VERSION || 'latest' }}"
          git push --set-upstream origin wheels

      - name: Trigger pages deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run pages.yml --ref main
